# -*- mode: ruby -*-
# vi: set ft=ruby :

# Change this to the amount of memory you want to allocate to your VM
MB=1024

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.network :forwarded_port, guest: 80, host: 8000, auto_correct: true
  config.vm.network :forwarded_port, guest: 3000, host: 3000, auto_correct: true
  config.vm.network :forwarded_port, guest: 3001, host: 3001, auto_correct: true
  config.vm.network :forwarded_port, guest: 4000, host: 4000, auto_correct: true
  config.vm.network :forwarded_port, guest: 8080, host: 8080, auto_correct: true

  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

  config.vm.provider :virtualbox do |vb|
    vb.name = "node-box"
    vb.memory = MB

    # Enable GUI for troubleshooting
    #vb.gui = true
  end

  config.vm.provision :shell, path: "provision.sh", privileged: false

end
